/*
*
* Copyright(c) 2018 Bohemia Interactive Simulations, Inc.
* http://www.bisimulations.com
*
* For information about the licensing and copyright of this software please
* contact Bohemia Interactive Simulations, Inc. at contact @ bisimulations.com.
*
*/
#ifndef EXAMPLESHOPPINGCART_PROXY_H
#define EXAMPLESHOPPINGCART_PROXY_H

/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
//WARNING
//This file has been autogenerated.
//Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#include <ComponentAPI.h>
#include <ExampleShoppingCartAPI.h>

GEARS_EXPORT void GEARS_API RegisterAPI_v1(APIManager_RegisterAPI_Func_v1 register_api);

#endif
