/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
//WARNING
//This file has been autogenerated.
//Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef EXAMPLESHOPPINGCART_PROXY_H
#define EXAMPLESHOPPINGCART_PROXY_H

#include <ComponentAPI.h>
#include <ExampleShoppingCartAPI.h>

GEARS_EXPORT void GEARS_API RegisterAPI_v1(APIManager_RegisterAPI_Func_v1 register_api);

#endif
