/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
//WARNING
//This file has been autogenerated.
//Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef EXAMPLESHOPPINGCART_H
#define EXAMPLESHOPPINGCART_H

#include <ComponentAPI.h>
#include <ExampleShoppingCartAPI.h>

APIResult GEARS_API Component_Initialize(_In_ const char* component_folder);
APIResult GEARS_API Component_OnStart(_In_ APIManager_v5* api_manager, _In_ NativeModuleHandle proxy_handle);
APIResult GEARS_API Component_OnStop();
APIResult GEARS_API Component_Shutdown();
APIResult GEARS_API Component_IsParallelizable(_Out_ bool32_t* parallelizable);
APIResult GEARS_API Component_GetName(_Inout_ int32_t* name_length, _Out_opt_ char* name);
APIResult GEARS_API Component_GetVersion(_Inout_ int32_t* version_length, _Out_opt_ char* version);

APIResult GEARS_API ExampleShoppingCart_AddItem(_In_ const char* item_name, _In_ float32_t price);

#endif
