/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
//WARNING
//This file has been autogenerated.
//Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#include "ExampleShoppingCartProxy.h"
#include "ExampleShoppingCart.h"

GEARS_EXPORT void GEARS_API RegisterAPI_v1(APIManager_RegisterAPI_Func_v1 register_api)
{
  //Register ComponentAPI_v5
  {
    static ComponentAPI_v5 api;
    APIInfo_v1 api_info;

    api.Initialize = Component_Initialize;
    api.OnStart = Component_OnStart;
    api.OnStop = Component_OnStop;
    api.Shutdown = Component_Shutdown;
    api.IsParallelizable = Component_IsParallelizable;
    api.GetName = Component_GetName;
    api.GetVersion = Component_GetVersion;

    api_info._api = &api;
    api_info._version = 5;

    register_api(ComponentAPI_Handle, &api_info);
  }

  //Register ExampleShoppingCartAPI_v1
  {
    static ExampleShoppingCartAPI_v1 api;
    APIInfo_v1 api_info;

    api.AddItem = ExampleShoppingCart_AddItem;

    api_info._api = &api;
    api_info._version = 1;

    register_api(ExampleShoppingCartAPI_Handle, &api_info);
  }
}
