#include "ExampleShoppingCartMock.h"

//Note:
//This file is partially autogenerated
//It is safe to make modifications to most of the file, however please don't modify the API function signatures
